# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Install clj
      run: |
        sudo apt-get install -y rlwrap
        curl -O https://download.clojure.org/install/linux-install-1.10.1.763.sh
        chmod +x linux-install-1.10.1.763.sh
        sudo ./linux-install-1.10.1.763.sh

    - name: Build release
      run: clj -M:dev release app

    - name: Prepare dir of just release files
      run: |
        mkdir -p out/js
        mv resources/public/index.html out/
        mv resources/public/js/main.js out/js/

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Copy files to the website with the AWS CLI
      run: |
        aws s3 sync ./out ${{ secrets.AWS_S3_BUCKET_URL }}

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
